[tool.poetry]
name = "zwo-efw"
version = "0.1.0"
description = "Python library for interacting with a ZWO EFW filter wheel over USB"
authors = ["Blake Mitchell <bmitc@mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
ruff = "^0.5.7"
poethepoet = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "I", # isort (sorting imports)
]
ignore = [
    "E712", # Prefer explicitness over implicitness
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
lines-after-imports = 2

[tool.poe.tasks]
all = ["format", "lint"]
format = ["format-code", "sort-imports"]
check-formatting = ["check-code-formatting", "check-imports"]
format-code = "poetry run ruff format ./zwo_efw ./tests"
check-code-formatting = "poetry run ruff format --check ./zwo_efw ./tests"
sort-imports = "poetry run ruff check --select I --fix"
check-imports = "poetry run ruff check --select I"
lint = "poetry run ruff check ./zwo_efw ./tests"

[tool.poetry.scripts]
move = "zwo_efw.scripts.move_filter_wheel:move"
